apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv
  namespace: zabbix
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path