apiVersion: v1
data:
  TZ: America/Maceio
  ZBX_CACHESIZE: 2048M
  ZBX_ENABLE_SNMP_TRAPS: 'true'
  ZBX_HANODENAME: zabbix-server
  ZBX_HISTORYCACHESIZE: 2048M
  ZBX_HISTORYINDEXCACHESIZE: 2048M
  ZBX_JAVAGATEWAY: zabbix-java-gateway
  ZBX_JAVAGATEWAY_ENABLE: 'true'
  ZBX_JAVAGATEWAYPORT: '10052'
  ZBX_LISTENPORT: '10051'
  ZBX_MAXHOUSEKEEPERDELETE: '5000'
  ZBX_NODEADDRESS: zabbix-server
  ZBX_PROBLEMHOUSEKEEPINGFREQUENCY: '60'
  ZBX_SERVICEMANAGERSYNCFREQUENCY: '60'
  ZBX_STARTDBSYNCERS: '10'
  ZBX_STARTHTTPPOLLERS: '1'
  ZBX_STARTJAVAPOLLERS: '5'
  ZBX_STARTPINGERS: '4'
  ZBX_STARTREPORTWRITERS: '3'
  ZBX_STARTTRAPPERS: '5'
  ZBX_TRENDCACHESIZE: 32M
  ZBX_VALUECACHESIZE: 128M
  ZBX_WEBSERVICEURL: http://zabbix-web-service:10053/report
kind: ConfigMap
metadata:
  labels:
    k8s-app: zabbix-server-1
  name: zabbix-server-1-envs
  namespace: zabbix